language: node_js
node_js:
- v8
before_install:
- openssl aes-256-cbc -K $encrypted_8469635b2593_key -iv $encrypted_8469635b2593_iv
  -in id_rsa.enc -out id_rsa -d
- npm i -g yarn
- yarn global add codecov
after_success:
- rm -rf ./coverage/clover.xml ./coverage/coverage-final.json ./coverage/lcov.info
  ./coverage/lcov-report
- codecov -e TRAVIS_NODE_VERSION
- yarn doc
- touch doc/.nojekyll
- gh-pages-travis
deploy:
  skip_cleanup: true
  provider: npm
  email: hourliert@gmail.com
  api_key:
    secure: pr+ZbM/k2uq6FXuiRZhldDdqcnL76nveG1vic2zueV3DVYIHOrD3Xn48q0noqqyl5HRljSEdfoGXnMerBzSCcoaVDmTrCYli/kKW2/BRkk7k8J8M/1Qcfif7bdKn7xI+fKjb4QTV89EJz/qatIx4+UFHtaBfmP2swvyvYtx754D08/kynQfAVbZvSmEtVYGA+5s7D+8c8Mz82KLDGNFEeCzIFy6ySoLUlhwDu+C5MOGhEg9o6+Lz9v3Q2H4ZlpUwi8uD1f6iUanqKmlo/c/d76c8tLVF/vKaRSrrViSNVVpX2YNwwCjvhvRG2X6AFye8pMZaYj6dJfsieBOMn7FuJFhb9oUsZBpruEAA1coRhzSaOkldgTArAzJvcVcXPpkALtGhpQ7LnEmDd/evwtl3jM3Z3tiWo/vaZfFYhlcHzo6Z4QZ/zY+DFwLetbvG1R71GqircA0/izUsJEV1tDKnybnpFCYkgJIqIFWsoET7det9q+MV9mUPJNB9UQySUav2kiUOstkUnuOyibM11e9VJSPvBP6RgJZR4uKDmfx9av4zIasq9c67GIGpZdg2w5kFr/CTyutR5qdgOdlN58NUbk+eWpLm0CVYQGbaUkxi2kIhcyh8N3trX+EleewHSlfr0xOjPqSjWdtOj3+DRGWnd7U107W2Mt0y9XB2GoMgBxU=
  on:
    tags: true
    repo: FoodMeUp/redux-crud-observable
branches:
  except:
  - gh-pages
env:
  global:
  - DEPLOY_BRANCH="master"
  - SOURCE_DIR="doc"
  - TARGET_BRANCH="gh-pages"
  - SSH_KEY="id_rsa"
  - GIT_NAME="travis"
  - GIT_EMAIL="deploy@travis-ci.org"
cache:
  yarn: true
